services:
  reth:
    image: ${RETH_IMAGE:-ghcr.io/paradigmxyz/reth:v1.8.3}
    restart: always
    environment:
      - RUST_LOG=${RETH_LOG_LEVEL:-info}
    stop_grace_period: 30s
    network_mode: host
    entrypoint: /root/init-script.sh
    env_file:
      - .env
    command:
      - node 
      - --chain=/config/genesis.json 
      - --datadir=/data
      - --http
      - --http.addr=0.0.0.0
      - --http.port=${EL_HTTP_PORT:-8545} 
      - --http.api=debug,web3,eth,txpool,net,admin
      - --http.corsdomain="*"
      - --ws 
      - --ws.addr=0.0.0.0
      - --ws.port=${EL_WS_PORT:-8546}
      - --ws.api=debug,web3,eth,txpool,net,admin
      - --ws.origins="*"
      - --authrpc.addr=0.0.0.0
      - --authrpc.jwtsecret=/config/jwtsecret
      - --nat=extip:${NODE_PUBLIC_IP}
#      - --p2p-secret-key-hex=/config/nodekey
      - --p2p-secret-key=/config/nodekey
      - --bootnodes=${EL_NODES}
      - --authrpc.port=${EL_AUTHRPC_PORT:-8551} 
      - --port=${EL_P2P_PORT:-30303} 
      - --discovery.port=${EL_P2P_PORT:-30303} 
    volumes:
        - ./data/reth:/data
        - ./config:/config
        - ./init-script.sh:/root/init-script.sh
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  beacon:
    image: sigp/lighthouse:v8.0.1
    restart: always
    network_mode: host
    env_file:
      - .env
    environment:
      - RUST_LOG=${LIGHTHOUSE_LOG_LEVEL:-info}
    stop_grace_period: 30s
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./data/lighthouse:/root/.lighthouse
      - ./config:/config
    command: >
      lighthouse beacon_node
      --testnet-dir /config
      --datadir /root/.lighthouse
      --http
      --http-address 0.0.0.0
      --http-port ${CL_HTTP_PORT:-5052}
      --execution-endpoint http://${NODE_PUBLIC_IP:-127.0.0.1}:${EL_AUTHRPC_PORT:-8551}
      --execution-jwt /config/jwtsecret
      --enr-udp-port ${CL_P2P_PORT:-9000} 
      --enr-tcp-port ${CL_P2P_PORT:-9000} 
      --port ${CL_P2P_PORT:-9000} 
      --http-allow-origin=*
      --listen-address=0.0.0.0
      --discovery-port 9000
      --suggested-fee-recipient=${FEE_RECIPIENT}
      --disable-enr-auto-update 
      --enr-address=${NODE_PUBLIC_IP}
      --staking
      --supernode
      --boot-nodes=${CL_NODES}
      --target-peers ${TARGET_PEERS:-64}
      --allow-insecure-genesis-sync
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
      
 #     --checkpoint-sync-url=https://checkpoin.labchain.la

  validator:
    image: sigp/lighthouse:v8.0.1
    security_opt:
      - seccomp:unconfined
    network_mode: host
    stop_grace_period: 30s
    env_file:
      - .env
    command:
      - lighthouse
      - vc
      - --debug-level=info
      - --testnet-dir=/config
      - --init-slashing-protection
      - --beacon-nodes=http://${NODE_PUBLIC_IP:-127.0.0.1}:${CL_HTTP_PORT:-5052}
      - --suggested-fee-recipient=${FEE_RECIPIENT}
      - --graffiti=${NODE_GRAFFITI}
    volumes:
      - ./data/lighthouse:/root/.lighthouse
      - ./config:/config
    depends_on:
      - beacon
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
